#!/bin/bash
wall=$(find ~/walls -type f | shuf -n 1)
swww img --transition-type any --transition-duration 1 --transition-fps 60 $wall
wal -i $wall
wal -i $wall -g
killall waybar
killall dunst
waybar & disown
zellijpywal
pywal-discord
pywalfox update
rm ~/.config/dunst/dunstrc
ln ~/.cache/wal/dunstrc ~/.config/dunst/dunstrc
dunst & disown
